### ISSUE TITLE
Project Maintenance Discussion

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#482] opened 2017-11-06 15:19 UTC
Since last year, due to other projects, interests and scholar obligations, I have less and less time to maintain this project. I initially started this project to familiar myself with Rust and I think I achieved that goal. I now have different interests where I want to invest some time in. Therefore, I don't have the bandwidth anymore to maintain this project. In the last months, a lot of people have shown interest in this project and have contributed. I appreciate that a lot! But at this point, I feel like I can't devote enough time to review issues and PRs within a time frame that I still consider to be respectful to the persons that contribute.

I don't want to block progress and leave contributors hanging, so I think it is time that I pass over the role of main maintainer to one or more interested persons.

@steveklabnik @budziq @frewsxcv @Michael-F-Bryan

**Comment by steveklabnik** [comment] 2017-11-06 19:04
Thank you for making this, and putting in all this work over such a long period of time! <3

I'm happy to at least help, but can't devote a *ton* of time; mostly working on stuff that's relevant to the features we use for the books in the rust distribution.

Given that we do use this internally, I wonder what the libs team would think about moving it to the nursery.

**Comment by Michael-F-Bryan** [comment] 2017-11-07 05:22
Thanks for everything you've done so far @azerupi! This has turned out to be a massively useful project and even now I use it all the time for documentation or writing up little guides on the side :)

I'm happy to put my hand up as a maintainer. Although it may also be a good idea to have two or three core maintainers to help share the load and increase the bus factor a bit.

**Comment by budziq** [comment] 2017-11-07 09:16
Thanks for this awesome project and all the help you have given the community!
Recently I'm finding myself with little free time to work on my Open Source commitments so taking on full maintainership here might be detrimental to the project :disappointed:. But I'll try to help out some more especially in the areas relevant to rust-cookbook.

I second Steve on puling the repo to rust-lang-nursery, this is a very important project for the rust community which makes writing high quality and consistent guides a breeze. Moving mdBook there would get more eyes and hands working on the project.

**Comment by Michael-F-Bryan** [comment] 2017-11-09 14:54
@steveklabnik, do you know what would be required to move mdbook to the nursery?

**Comment by budziq** [comment] 2017-11-09 15:16
> do you know what would be required to move mdbook to the nursery?

From purely technical point. @azerupi Will have to initiate the transfer to rust-lang-nursery account and one of the org members will have to accept. 

From the logistics point of view I'm guessing that Steve will discuss the issue with libs team if they are interested in accepting the ownership.

**Comment by steveklabnik** [comment] 2017-11-09 15:56
Yes, that's correct. I actually even have permissions over there, IIRC, so
it's really just the social bit. I'm travelling right now so it's a bit
complicated for me, but should be able to find out in the next week or so.

**Comment by azerupi** [comment] 2017-11-09 16:37
>Given that we do use this internally, I wonder what the libs team would think about moving it to the nursery.

That would be awesome, I would be honored. :)
When you have more information about that, let me know so that I transfer the repository. In the mean time, @Michael-F-Bryan I will add you as a maintainer!

**Comment by Michael-F-Bryan** [comment] 2017-11-10 04:18
> In the mean time, @Michael-F-Bryan I will add you as a maintainer!

Awesome! In the meantime I've got a couple hours to kill so I might start doing a couple code reviews. I'm in the same boat as @budziq though in that I'm more of a systems-level programmer than a front-end dev.

**Comment by steveklabnik** [comment] 2017-11-11 13:58
I've gotten the green light to transfer it; feel free to initiate whenever you have time, @azerupi !

Basically, it will be similar to rustdoc: committers to mdbook will be "tool peers" under the devtools/doc team. :)

**Comment by Michael-F-Bryan** [comment] 2017-11-11 14:01
> Basically, it will be similar to rustdoc: committers to mdbook will be "tool peers" under the devtools/doc team. :)

Just out of curiosity, what is a "tool peer"?

**Comment by steveklabnik** [comment] 2017-11-11 14:04
It's something slightly less than "team member", that is, you're a team member *for that tool* rather than for the team as a whole. It's jargon specific to the dev-tools team.

**Comment by budziq** [comment] 2017-11-11 14:06
Basically you retain the collaborator/commit rights to the repo

**Comment by Michael-F-Bryan** [comment] 2017-11-11 15:18
> you're a team member for that tool rather than for the team as a whole

Sounds good to me :+1:

I guess the big question is... How will this affect the project from an organisational/logistical standpoint?

As it stands I really like what this project does and have a couple core features I'd like to see incorporated in some day (e.g. alternate backends and plugins), so I'm more than happy to keep helping out.

**Comment by steveklabnik** [comment] 2017-11-11 15:34
> I guess the big question is... How will this affect the project from an organisational/logistical standpoint?

Basically, those of us who are maintainers operate on rough consensus. It feels to me like mdbook already works that way, so it shouldn't be a big change. The other difference is that the URL to the repo changes. That's about it though.

**Comment by budziq** [comment] 2017-11-11 16:15
> have a couple core features I'd like to see incorporated in some day

Yeah some of your PR's are long overdue for final review and merging. Probably will need to get more focus on reducing that backlog.

As long as we don't introduce regressions I'm game with any new features.
Lets stick to some minimal discussion prior to merging significant changes and we'll do just fine 👍

**Comment by azerupi** [comment] 2017-11-12 10:01
@steveklabnik I tried to transfer it to rust-lang-nursery but it failed because I don't have the permissions to create a repository on that organization. So I think it's best that I first transfer the repo under your name so that you can transfer it to the organization? :)

**Comment by steveklabnik** [comment] 2017-11-12 11:00
Sure thing!

**Comment by azerupi** [comment] 2017-11-12 11:41
Damn, looks like I can't do that either because it already exists (as a fork) 😅
I think you first need to delete your fork before I can transfer the repo. GitHub makes this way more complicated than it should be... 😋

**Comment by steveklabnik** [comment] 2017-11-12 12:11
Deleted!

**Comment by azerupi** [comment] 2017-11-12 12:30
Done! Thanks a lot :)

**Comment by steveklabnik** [comment] 2017-11-12 12:42
Boom! https://github.com/rust-lang-nursery/mdbook

**Comment by azerupi** [comment] 2017-11-12 12:45
Excellent!
I suppose we need to setup Travis, Appveyor and GitHub pages again for the new repo?

**Comment by steveklabnik** [comment] 2017-11-12 12:49
I'm not sure; given that you had permissions with the old repo.... here, let me open a PR and we'll see!

**Comment by Michael-F-Bryan** [comment] 2017-11-18 15:50
Looks like someone in the rust-lang-nursery organisation will have to move appveyor across. Even though I've got commit rights to this repo it doesn't look like appveyor will let me add anything to rust-lang-nursery's builds.

cc: @rust-lang-nursery

**Comment by budziq** [comment] 2017-11-18 16:56
Given how many hoops we had to jump through with Alex to give me permissions for cookbook appveyor (without me joining nursery org) I'd suggest to just leave appveyor where it is as long as it works and we can trigger builds.

**Comment by Michael-F-Bryan** [comment] 2017-11-18 17:10
I was thinking it may be easier to ask someone already part of the nursery organisation to move things across, seeing as it's a one-time thing. 

> I'd suggest to just leave appveyor where it is as long as it works and we can trigger builds.

It doesn't look like the CI hooks are working any more because the repo's URL has changed. If you go to any recent PR and scroll to the bottom it's only firing off travis builds, meaning there's no guarantee that any changes we make work on windows.

A recent PR:

![screenshot_2017-11-19_010810](https://user-images.githubusercontent.com/17380079/32982868-21462948-ccc6-11e7-8b2b-8a2656515617.png)

A PR from before the move:

![screenshot_2017-11-19_010910](https://user-images.githubusercontent.com/17380079/32982879-48b487ea-ccc6-11e7-934d-3181d5c5f847.png)

**Comment by budziq** [comment] 2017-11-18 17:40
Ouch! Then we need to move then. I'll try to dig up the steps we've done to allow me administrative access on cookbook appveyor (being collaborator is not enough, we'll need an additional account on appveyor)

**Comment by steveklabnik** [comment] 2017-11-19 01:12
I'm an owner of the nursery, I can do this.

I've been at conferences and on vacations so have been a bit MIA, but am
back now. Likely to catch up with the huge backlog monday. If you take care
of this before then, great, but if not, I'll do it then :)

On Sat, Nov 18, 2017 at 12:40 PM, Michał Budzyński <notifications@github.com

**Comment by budziq** [comment] 2017-11-19 16:32
> If you take care
of this before then, great, 


https://github.com/rust-lang-nursery/rust-cookbook/issues/238#issuecomment-323971979

**Comment by Michael-F-Bryan** [comment] 2017-12-11 08:02
What do we need to make appveyor push compiled artefacts to GitHub releases? It seems like the easiest way to handle #481.

**Comment by Michael-F-Bryan** [comment] 2017-12-26 14:21
Do you guys know anyone who'd be interested in helping on the frontend side of mdbook? Recently [I noticed] that a PR I'd merged introduced a regression and although it was mostly negligence on my part (I didn't test it as thoroughly as I should have), "silly" issues like that could probably be prevented if there were more eyes.

[I noticed]: https://github.com/rust-lang-nursery/mdBook/pull/501#issuecomment-353972637

**Comment by projektir** [comment] 2017-12-27 03:01
@Michael-F-Bryan 
I worked a little bit on the frontend side, I could perhaps help with reviews.

**Comment by Michael-F-Bryan** [comment] 2017-12-30 10:19
I've just realised that when merging #457 we should have gone to `0.1.0` instead of doing a patch release (updating `book.toml` largely broke the format's backwards compatibility), so I'm thinking we should do a major version bump fairly soon. Unfortunately I need `pulldown-cmark` to make a patch release before that can happen (https://github.com/google/pulldown-cmark/pull/118#issuecomment-350647909).

I've also implemented most of the stuff necessary for alternate backends (#507) and am fairly confident (https://github.com/rust-lang-nursery/mdBook/pull/507#issuecomment-354537764) it's the right way to do things in the long term. If possible, I'd like to include that in any upcoming `0.1` release because it gives us a really good foundation for implementing things like plugins (e.g. pre/post processing before rendering) and alternate backends.

Does anyone have any thoughts or opinions on doing a major semver bump and including the alternate backends mechanism?

**Comment by projektir** [comment] 2018-01-18 03:25
@Michael-F-Bryan I think a new release (as I understand a major semver bump should result in this?) is a good idea, and we could also address #481 then.

**Comment by Michael-F-Bryan** [comment] 2018-01-18 04:06
Yeah, I really want to do another release but I'm still waiting for `pulldoen_cmark` to make another release (https://github.com/google/pulldown-cmark/pull/118#issuecomment-350647909). I guess I could always make a temporary workaround so we can release, then revert it later on. Thoughts?

**Comment by Michael-F-Bryan** [comment] 2018-01-18 04:11
We also need to get Appveyor working again so we test PRs against Windows and make sure it can do releases. It's still pointing at the old location, `azerupi/mdbook`, and because I'm not part of the rust-lang-nursery organisation I can't set it up again. It's a 5 minute job, I just don't have the right permissions to do it 😞 

If anyone knows someone on the infra team, would you be able to CC them into this conversation? 

CC: @rust-lang-nursery

**Comment by projektir** [comment] 2018-01-18 04:13
`pulldown_cmark` repo looks a bit inactive to me right now... last activity was December 10th. I don't know if I want to say "work off of a fork for now", or how difficult the temporary workaround would be, but I'm not really much for waiting for other repositories.

@steveklabnik, @Mark-Simulacrum 
You know who can help setup AppVeyor for `rust-lang-nursery/mdbook`?

**Comment by Michael-F-Bryan** [comment] 2018-01-18 04:33
> I don't know if I want to say "work off of a fork for now",..., but I'm not really much for waiting for other repositories.

Agreed. I'll probably be able to make a PR with the workaround after work tonight.

**Comment by Mark-Simulacrum** [comment] 2018-01-18 21:56
cc @alexcrichton @aturon -- we'll probably need your help with setting up AppVeyor for this repository.

**Comment by alexcrichton** [comment] 2018-01-18 22:14
It's [now enabled](https://ci.appveyor.com/project/rust-lang-libs/mdbook)

**Comment by Michael-F-Bryan** [comment] 2018-01-19 15:48
> It's now enabled

Awesome! Is there any chance you'd be able to make a PR updating the badge in the README? It seems appveyor use some sort of hash/uuid as the image URL for a project's badge instead of just the project's name.

**Comment by Michael-F-Bryan** [comment] 2018-01-31 11:08
@alexcrichton, would you happen to have the snippet for `mdbook`'s Appveyor badge? I just noticed we've still got the old `azerupi/mdbook` badge at the top of our README.

Also I don't believe we've got any Windows binaries in the releases, so we may have to update the API key for Appveyor or `appveyor.yml`. Anyone know the best way to do this?

**Comment by alexcrichton** [comment] 2018-01-31 15:06
https://gist.githubusercontent.com/Zoxc/7c4a288fa4143385efcdadfd16638a75/raw/6bc6e40daaa82361643b6244dd3b69aaa37b3185/gistfile1.txt

**Comment by alexcrichton** [comment] 2018-01-31 15:06
er, [![Build status](https://ci.appveyor.com/api/projects/status/ysyke2rvo85sni55?svg=true)](https://ci.appveyor.com/project/rust-lang-libs/mdbook)

**Comment by Michael-F-Bryan** [comment] 2018-05-01 12:50
@steveklabnik, what's the usual process for adding people as maintainers to a `rust-lang-nursery` repository? After reading through the [Bus Factor +1 thread][1] on the user forums it may be beneficial to add another co-maintainer to `mdbook` to help handle all the PRs and issues.

[1]: https://users.rust-lang.org/t/bus-factor-1-for-crates/17046/13

**Comment by carols10cents** [comment] 2019-04-28 19:32
I'm going to close this given that maintainership is changing again, see #858, so I think this instance of maintainership transfer has been completed ❤️

**Closed by carols10cents** 2019-04-28 19:32 UTC
Labels: M-Discussion
