### ISSUE TITLE
Page content overlaps search bar after search term is erased

### ISSUE THREAD

**Issue by mattico** [rust-lang-nursery/mdBook#647] opened 2018-03-19 20:10 UTC
If you search for something then erase the search term the content reappears and overlaps the search bar.

![image](https://user-images.githubusercontent.com/853158/37619356-474303c6-2b87-11e8-8738-5094ea85bd5d.png)

**Comment by Michael-F-Bryan** [comment] 2018-04-11 02:27
Looks like this wasn't completely fixed in #648 (it still happens when the sidebar is shown, see #666), and my "solution" of setting the search box to be `display: block` only seems to work on chrome so I've reverted it 😞

@mattico or @sorin-davidoi, do you have any ideas?

**Comment by mattico** [comment] 2018-04-11 02:30
@Michael-F-Bryan I'll take a look.

**Comment by mattico** [comment] 2018-04-11 02:38
I can't reproduce this issue with current master. Windows 10 - Firefox, Chrome, Edge. Sidebar or no. Could this be a macOS specific issue, somehow? Perhaps something with hidpi screens?

**Comment by mattico** [comment] 2018-04-11 02:40
Going to try Ubuntu...

**Comment by Michael-F-Bryan** [comment] 2018-04-11 02:55
@mattico, thanks a lot for looking into this!

At work (Windows 10, Firefox) I was using `mdbook` and noticed the search bar was messed up, so I installed directly from `master` () and deleted my browser cache, and the issue was still there.

Now that I've checked out the `mdbook` repository, recompiled everything, and opened the example book, everything renders fine and I can't seem to reproduce the issue ¯\_(ツ)_/¯

**Comment by Michael-F-Bryan** [comment] 2018-04-11 02:56
If you can't reproduce on Windows or Ubuntu and it's working fine again on my computer, should we write this off as either unreproducible or some sort of caching issue?

**Comment by mattico** [comment] 2018-04-11 03:46
Yeah, Ubuntu's fine. I'm pretty confident in writing this off as a caching issue. If it's not, I'm sure we'll hear about it. Also this issue is present in the current release so we're not regressing either way.

**Comment by azerupi** [comment] 2018-04-16 00:10
I can't reproduce this with the current master either (I noticed the bug in the latest crates.io release). Let's close this issue for now, we can still re-open it later if we notice that it isn't resolved.

**Closed by azerupi** 2018-04-16 00:10 UTC
