### ISSUE TITLE
thread 'main' panicked at 'byte index 1 is not a char boundary

### ISSUE THREAD

**Issue by flodolo** [rust-lang-nursery/mdBook#971] opened 2019-07-04 09:54 UTC
I'm running mdBook 0.3 on macOS, and for some reasons it fails to build one of the file containing the ë character. The thing I don't understand is that I have other files with that character, and they build just fine.

Minimal file content in README.md

```
# Test

spatiëring.
```

Error

```
2019-07-04 11:52:26 [INFO] (mdbook::book): Book building has started
2019-07-04 11:52:26 [INFO] (mdbook::book): Running the html backend
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ë' (bytes 0..2) of `ër`', src/libcore/str/mod.rs:2027:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by flodolo** [comment] 2019-07-04 10:02
Additional note: it doesn't seem to happen if the content of the file is just

```
spatiëring.
```

**Comment by zbraniecki** [comment] 2019-07-05 16:47
Any chance you can run it with `RUST_BACKTRACE=1` to get the trace?

**Comment by flodolo** [comment] 2019-07-05 16:55
```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ë' (bytes 0..2) of `ër`', src/libcore/str/mod.rs:2027:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::str::slice_error_fail
   9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
  10: elasticlunr::lang::en::stemmer
  11: elasticlunr::pipeline::Pipeline::run
  12: elasticlunr::Index::add_doc
  13: mdbook::renderer::html_handlebars::search::add_doc
  14: mdbook::renderer::html_handlebars::search::create_files
  15: <mdbook::renderer::html_handlebars::hbs_renderer::HtmlHandlebars as mdbook::renderer::Renderer>::render
  16: mdbook::book::MDBook::build
  17: mdbook::cmd::build::execute
  18: mdbook::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: main
```

**Comment by zbraniecki** [comment] 2019-07-05 17:00
Ok, seems to be a bug in https://github.com/mattico/elasticlunr-rs

Basically, it doesn't expect english to use non-latin characters.

The kind of code that triggers the crash is https://github.com/mattico/elasticlunr-rs/blob/master/src/lang/en.rs#L213

It should instead use a safe slicing, and likely a different regexp.

**Comment by flodolo** [comment] 2019-07-05 17:03
Thanks for digging. I assume the best next step is to report the issue in the other repository?

**Comment by bwinton** [comment] 2019-07-05 18:24
The full backtrace is:
```
---- mdbook_runs_renderers stdout ----
thread 'mdbook_runs_renderers' panicked at 'byte index 1 is not a char boundary; it is inside 'ë' (bytes 0..2) of `ër`', src/libcore/str/mod.rs:2027:5
[snip…]
  13: elasticlunr::lang::en::Stemmer::stem
             at /Users/bwinton/.cargo/registry/src/github.com-1ecc6299db9ec823/elasticlunr-rs-2.3.4/src/lang/en.rs:225
  14: elasticlunr::lang::en::Stemmer::stem::{{closure}}
             at /Users/bwinton/.cargo/registry/src/github.com-1ecc6299db9ec823/elasticlunr-rs-2.3.4/src/lang/en.rs:305
  15: elasticlunr::pipeline::tokenize::{{closure}}
             at /Users/bwinton/.cargo/registry/src/github.com-1ecc6299db9ec823/elasticlunr-rs-2.3.4/src/pipeline.rs:58
  16: <alloc::string::String as core::ops::arith::Add<&str>>::add
             at /Users/bwinton/.cargo/registry/src/github.com-1ecc6299db9ec823/elasticlunr-rs-2.3.4/src/lib.rs:259
  17: mdbook::renderer::html_handlebars::search::add_doc
             at src/renderer/html_handlebars/search.rs:63
  18: mdbook::renderer::html_handlebars::search::render_item
             at src/renderer/html_handlebars/search.rs:162
  19: mdbook::renderer::html_handlebars::search::create_files
             at src/renderer/html_handlebars/search.rs:20
  20: mdbook::renderer::html_handlebars::hbs_renderer::maybe_wrong_theme_dir::entry_is_maybe_book_file
             at src/renderer/html_handlebars/hbs_renderer.rs:361
  21: mdbook::book::MDBook::render
             at src/book/mod.rs:230
  22: mdbook::book::MDBook::execute_build_process
             at src/book/mod.rs:214
  23: core::char::convert::from_u32_unchecked
             at src/book/mod.rs:178
  24: build_process::mdbook_runs_renderers
             at tests/build_process.rs:74
  25: build_process::mdbook_runs_renderers::{{closure}}
             at tests/build_process.rs:66
[snip…]
```

I've made [a pull request](https://github.com/mattico/elasticlunr-rs/pull/23) to elasticlunr-rs that looks like it'll fix this issue.

**Comment by zbraniecki** [comment] 2019-07-05 19:04
Thanks Blake! That looks like a good fix.

**Comment by bwinton** [comment] 2019-07-11 17:24
And [the PR](https://github.com/mattico/elasticlunr-rs/pull/23) has landed, so hopefully this will be fixed when we pull in the next version of that library! 😃

**Closed** 2019-07-13 04:59 UTC
Labels: T-Dependency-bug

**Comment by szabgab** [comment] 2025-03-17 06:11
I noticed your code uses elasticlunr-rs v3.0.3 that was released 7 hours ago. mdbook currently uses elasticlunr-rs v3.0.2
That probably means you installed mdbook using `cargo install mdbook`

First thing you can try is installing mdbook as `cargo install mdbook --lock` or to install the binary and let us know if the problem persists. You can probably also report it on elasticlunr-rs

**Comment by EUSKR** [comment] 2025-03-19 02:22
Thank you, @szabgab , using --locked solved the problem indeed (binary also worked fine), so I guess it's the elasticlunr 3.0.3 that caused a regression. Let me try reporting it to them.

**Comment by jobarr-amzn** [comment] 2025-03-19 15:50
@EUSKR I put a PR out to fix this issue. It looks like [rust-stem](https://github.com/minhnhdo/rust-stem) picked up this bug fix a couple years ago in minhnhdo/rust-stem#9, not long after rust-stem's implementation was ported into elasiclunr-rs in https://mattico/elasticlunr-rs#48 .

Hopefully the recent activity in elasiclunr-rs means someone may take the PR, but in the mean time @szabgab thanks for the recommendation to use `--locked`.
