### ISSUE TITLE
Building books fails since 0.0.27

### ISSUE THREAD

**Issue by teiesti** [rust-lang-nursery/mdBook#505] opened 2017-12-07 20:33 UTC
For some strange reason, building books with mdBook fails since version 0.0.27. If I try, this is what happens:

```
> mdbook build
An error occured:
Unable to open the configuration file
```

If I create a new empty book with `mdbook init` and try `mdbook build` after, building fails.
If I try `mdbook watch`, building fails.

If I try the previous version 0.0.26, everything works just fine.

I am using the most recent version of Rust: `rustc 1.22.1 (05e2e1c41 2017-11-22)`.

**Comment by Michael-F-Bryan** [comment] 2017-12-09 10:25
This is fixed in #506. It seems I didn't tell `mdbook` to use the default `Config` if `book.toml` is found, and our tests didn't pick up the regression because the books being tested all have a `book.toml`.

I've made a `0.0.28` release, so it should work now.

**Closed** 2017-12-09 10:26 UTC

**Comment by steveklabnik** [comment] 2017-12-09 15:33
Thanks! :)

**Comment by teiesti** [comment] 2017-12-10 18:29
Works fine! Thanks a lot!
