### ISSUE TITLE
bug: can't back to chapter after toggle the content on mobiles

### ISSUE THREAD

**Issue by huangjj27** [rust-lang-nursery/mdBook#459] opened 2017-10-01 04:25 UTC
as is shown in the image follow, when I toggle the content, I can't back to the chapter that I was reading:
![image](https://user-images.githubusercontent.com/8068443/31051746-67a5b41a-a6a3-11e7-815a-f86f0308354e.png)

also, the printer icon also _shouldn't appear in the content.

please fix the bug soon!

**Comment by jacwah** [comment] 2017-10-09 11:09
Can reproduce in Chrome devtools with small screens. The reason is that sidebar has a fixed width of 300px, which is too wide for e.g. an iPhone 5 with screen width of 320px.

https://github.com/azerupi/mdBook/blob/c64384abc3df85354f524332d91d3d286bf8d4c3/src/theme/stylus/variables.styl#L1

**Comment by budziq** [comment] 2017-10-10 23:44
Thanks for reporting this issue @huangjj27!

This looks like a regression, we used to have this **exact** usecase under control.

Untill the issue is resolved you can either:
- Select onenof the chapters to close the sidebar
- Scroll horizontally to the right exposing the hamburger menu

Probably we need to have sidebar width bounded between 300px and screen width percent.

Would you be interested in looking into this problem further @jacwah?

**Comment by huangjj27** [comment] 2017-10-11 01:10
> Probably we need to have sidebar width bounded between 300px and screen width percent.
@budziq I think you could make it responsive and just make the toc button shown in the right edge, as the gitbooks does.

**Comment by budziq** [comment] 2017-10-11 08:31
Good call! We are very low on webdev contributors (I am certainly not one ;) so the idea did not even occur to me)

**Comment by huangjj27** [comment] 2017-10-11 09:33
@budziq 
> We are very low on webdev contributors
It's not about the skill level of software development, but the real usage story of the product. I'm a user, as well as a tester, and thus I could more easily know what I really want.

**Comment by jacwah** [comment] 2017-10-11 12:29
I'll look into it!

@budziq Do you know a point when this was working?

**Comment by budziq** [comment] 2017-10-11 14:25
@jacwah I've just done a quick bisect. Unfortunately it is not a regression but a persisting bug. We have tested only with mobile screen sizes of iPhone6 and up (I just remembered that there was commit fixing the layout for screen sizes of iPhone6 and up).

The layout was always broken on lower screen sizes. So my bad for misinforming you.

**Comment by jacwah** [comment] 2017-10-13 19:42
I've looked at a responsive solution using `calc`. Due to my lacking experience with CSS and Stylus being completely new to me I haven't gotten it to work.

A quick fix is to just reduce the width. Something responsive seems like a more appropriate and long-term solution though.

**Comment by Michael-F-Bryan** [comment] 2018-01-03 02:44
This problem of being unable to close the menu was fixed in #474 and #470.

**Closed by Michael-F-Bryan** 2018-01-03 02:44 UTC

**Comment by huangjj27** [comment] 2018-02-11 12:26
the solution works, and thanks!

beside, I think to make the toc button keep fixed displayed on the top right corner is a better solution to improve the user experience. 
![default](https://user-images.githubusercontent.com/8068443/36073334-d0d2c8e0-0f69-11e8-9434-6a9995fb1789.png)
