### ISSUE TITLE
Printout of "The Rust Programming Language" is truncated

### ISSUE THREAD

**Issue by jimis** [rust-lang-nursery/mdBook#840] opened 2018-12-05 00:20 UTC
Using Firefox, go to "The Rust Programming Language" manual page and click on the print button on the upper right corner of the page. This redirectos to a printable page with the whole manual, and a bit later the print dialog pops-up, so select "print to PDF". The full URL is this:

https://doc.rust-lang.org/book/2018-edition/print.html

Results: The margins in the generated PDF file are messed up. The left half of the page is empty, the right half is missing (text is truncated in all pages). See attachment "mozilla.pdf", which is a printout of the first 10 pages of the manual.

[mozilla.pdf](https://github.com/rust-lang/rust/files/2643702/mozilla.pdf)

**Comment by jwatt** [comment] 2019-01-02 22:56
I ended up here from https://bugzilla.mozilla.org/show_bug.cgi?id=1511461

While debugging to figure out if this was a Mozilla or mdBook bug I discovered that the issue is fixed in the latest version of the book:

https://doc.rust-lang.org/book/print.html

**Comment by jimis** [comment] 2019-01-04 17:01
@jwatt the PDF looks the same to me even with the latest version of the book.

I found a workaround though: 
* Close the print dialog that automatically pops-up
* Hide the table-of-contents sidebar by hitting the button in the upper-left corner
* Print manually

**Comment by ehuss** [comment] 2019-05-17 15:24
This seems to be fixed in the latest mdbook.  For example: https://doc.rust-lang.org/nightly/book/print.html works. TRPL was updated to mdbook 0.2 just recently (https://github.com/rust-lang/rust/pull/59876), and will ride the train with rust 1.36.

**Closed by ehuss** 2019-05-17 15:24 UTC

**Comment by jimis** [comment] 2019-05-17 16:59
Indeed the nightly version of the book prints nicely. Thanks!
