### ISSUE TITLE
links in SUMMARY.md should be able to target anchors

### ISSUE THREAD

**Issue by seanjensengrey** [rust-lang-nursery/mdBook#632] opened 2018-02-25 17:35 UTC
Links in the SUMMARY.md file should be able to target anchors in an existing or new document.

```
# Summary

[Introduction](index.md)

- [Hello World](hello.md)
    - [Comments](hello.md#comment-section)
```

The `Comments` entry in the above snippet should generate to link to `hello#comment-section` in backends that support it.

As of mdbook 0.1.3  when referencing the same file twice in a `SUMMARY.md`, the entire document `hello.md` fails to render. 

The goal is to have a more detailed sidebar table of contents (ToC) w/o splitting each heading into its own file.

**Comment by seanjensengrey** [comment] 2018-02-25 18:18
Anchor links are defined in `pulldown-cmark` [here](https://github.com/google/pulldown-cmark/blob/6de6f220dd51dab2b2d44269aa37ff740cbdae27/tests/spec.rs#L11599)

**Comment by folex** [comment] 2019-02-27 10:50
Please do! This would enable to include ToC of a specific document to the main ToC.

**Comment by ehuss** [comment] 2019-05-17 13:14
Closing as duplicate of #167.

**Closed by ehuss** 2019-05-17 13:14 UTC
Labels: A-Links
