### ISSUE TITLE
Inconsistencies escaping pipes in a code tag in a table

### ISSUE THREAD

**Issue by Fierthraix** [rust-lang-nursery/mdBook#637] opened 2018-03-06 02:19 UTC
## Problem
You have a table that you want to look like this

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1|[3-5])|bar-([39]|39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

It has some code with pipes in it.

### Attempt 1

Your initial solution is just to put the code in the table

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|`foo-(1|[3-5])|bar-([39]|39)`|`foo-1`, `bar-39`|
```

which actually renders as:

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td>`foo-(1</td><td>[3-5])</td><td>bar-([39]</td><td>39)`</td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

because every pipe gets interpreted as a table column. 

### Attempt 2
The next logical step is to add an escape `\` before the `|`
```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|`foo-(1\|[3-5])\|bar-([39]\|39)`|`foo-1`, `bar-39`|
```

Which escapes the `|`, but also magically renders your escape `\`!

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1\|[3-5])\|bar-([39]\|39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

This prevents the pipe from being interpreted as a part of the table, but prints the backslash for some reason! This makes it seem like that with pure markdown there is no way to escape the pipe without printing the escape character.

### Using HTML

You decide to put inline HTML and replace the backtick with a `<code>` tag (sans escape backslashes on the pipe)

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|<code>foo-(1|[3-5])|bar-([39]|39)</code>|`foo-1`, `bar-39`|
```
which renders as:

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1</td><td>[3-5])</td><td>bar-([39]</td><td>39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

This doesn't print the backticks like in the first attempt, and actually shades the first cell as being code. The problem being that we now have pipes making new columns again! 
This is the only example so far that works as we would've expected for a parser that doesn't search for the closing tag.

### `<code>` tag with escape backslash

Using HTML was an improvement, so what if we try out the escape backslashes again?

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|<code>foo-(1\|[3-5])\|bar-([39]\|39)</code>|`foo-1`, `bar-39`|
```

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1\|[3-5])\|bar-([39]\|39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

Success! Using `<code>` tags in conjunction with escape backslashes produces the desired result.

### Rendering without inline code
To constrast this with how markdown renders outside of code tags, using an escape backslash works exactly as expected:

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|foo-(1\|[3-5])\|bar-([39]\|39)|`foo-1`, `bar-39`|
```

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td>foo-(1\|[3-5])\|bar-([39]\|39)</td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

My guess for this is that when a backtick is detected in a table, the table mode searching for unescaped pipes doesn't switch off for unescaped backslashes, leading to the results above.

## Expected Results:
You would expect that when you insert a code backtick that everything between the <code>\`  \`</code> isn't affected by what context it is in (in this case a table). This is desirable because it is frustrating to have to be aware that what characters you have to escape depends on what kind of structure you already have.

If this is not realizable/goes against the current standard then at the very least I think that using the escape backslash before a pipe should **not** render.

P.S. attached is a markdown file that contains the examples in this issue (saved as a `.txt` because github wouldn't let me up load a markdown file)
[chapter_1.txt](https://github.com/rust-lang-nursery/mdBook/files/1783239/chapter_1.txt)

P.P.S. It was very difficult to correctly render incorrectly rendering markdown using a differently flavoured markdown | ￣ヘ￣|

**Comment by Michael-F-Bryan** [comment] 2018-03-15 13:06
I'm going to close this seeing as an issue has been made upstream.

**Closed by Michael-F-Bryan** 2018-03-15 13:06 UTC

**Comment by learnbyexample** [comment] 2020-08-15 11:17
I ran into this problem as well.

The linked upstream issue is closed as does a newer issue https://github.com/raphlinus/pulldown-cmark/issues/446

Can a workaround be implemented in mdBook? May be use a configuration option in `book.toml` so that the patch has to be explicitly enabled to avoid breaking current behavior?

**Comment by ehuss** [comment] 2020-08-15 20:31
It would be best to fix pulldown-cmark. I haven't looked, but I can't imagine it is *too* difficult. For now, you can use HTML fragments like `<code>&vert;</code>`.

**Comment by learnbyexample** [comment] 2020-08-17 04:55
Yeah, I already had pre and post processing scripts, which I'm modifying to fix all table entries having `\|` inside an inline code snippet. The problem is I have expressions like `/\((?:[^()]++|\g<0>)++\)/` and I had to visually inspect the result of conversion to arrive at `<code>/&#92;((?:[&#94;()]++&#124;&#92;g<0>)++&#92;)/</code>` and I don't know what other corner cases exist.

I have another suggestion - would it be possible to configure the engine used to convert markdown to html? For example, if `pandoc` can be integrated (either as part of `mdbook` binary itself or as an external call to `pandoc` binary), then user can specify which flavor of markdown is being used as well as the various other conversions `pandoc` supports.

**Comment by your-diary** [comment] 2022-10-10 15:21
Any updates?
