### ISSUE TITLE
Expand links properly when cross linking to other `.md` files

### ISSUE THREAD

**Issue by udoprog** [rust-lang-nursery/mdBook#588] opened 2018-01-26 17:13 UTC
Hey,

It seems like mdbook doesn't translate links in chapters (like `[link to chapter2](../chapter2.md)) to the resulting html file. To work around this, you have to use a link relative to the output folder, like `chapter2.html`.

This breaks markdown links which are hosted on GitHub, and generally also means that a mdbook author needs to understand the topology of the generated book, instead of its sources when cross linking.

Examples:
* https://github.com/rust-lang-nursery/mdBook/blame/master/book-example/src/cli/init.md#L25
* https://github.com/rust-lang/book/blame/master/second-edition/src/ch02-00-guessing-game-tutorial.md#L262

I was not able to find an existing issue that mentioned this, but I didn't look super close. At least this should help in future searching.

**Comment by Michael-F-Bryan** [comment] 2018-01-27 05:32
> I was not able to find an existing issue that mentioned this, but I didn't look super close. At least this should help in future searching.

I believe this is the same as #431. The idea is you should be able to link to the source file (e.g. `foo.md`) and then a `Preprocessor` will go through and rewrite the `md` extension to `html` before it gets sent to the renderer. 

Now `Preprocessors` have landed we can make progress on implementing this properly, instead of hacking something on top of markdown-to-html rendering.

> mdbook author needs to understand the topology of the generated book, instead of its sources when cross linking

The generated book is guaranteed to have the same structure as the source documents. So you should be able to use `*.html` instead of `*.md` and everything will work.

**Comment by Michael-F-Bryan** [comment] 2018-01-27 06:11
I think I'll close this as a duplicate of #431.

**Closed by Michael-F-Bryan** 2018-01-27 06:11 UTC

**Comment by udoprog** [comment] 2018-01-27 11:15
Ok. Thanks!
