### ISSUE TITLE
I cannot get the new links to work

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/mdBook#828] opened 2018-11-20 18:02 UTC
I'm working on updating the rust docs to use the mdbook 0.2 series.

In https://github.com/rust-lang-nursery/mdBook/pull/603 the new link strategy was implemented.

I can get a link to work, but then the print page is broken. See https://raw.githubusercontent.com/rust-lang/rust/master/src/doc/unstable-book/src/language-features/asm.md for example:

    If you need more power and don't mind losing some of the niceties of
    `asm!`, check out [global_asm](language-features/global-asm.html).

Changing this to either of

    global-asm.md
    ../language-features/global-asm.md

means that the print page's link is broken.

@cetra3 you implemented this, and @Michael-F-Bryan you merged it. Any ideas?

**Comment by cetra3** [comment] 2018-11-20 23:04
I've managed to reproduce this in some cases.  It looks like the print output is not dealing with relative links, rather the output of each page is not different when printing vs. normal page output.

**Comment by steveklabnik** [comment] 2019-01-14 15:47
Okay, so I think, after doing some investigations, the issue is basically that:

1. because the links used to be relative to the root, they happened to work for print.html, because it was at the site root
2. now that links are not relative to the root, they no longer work.

This means that we need some sort of "URL normalization" pass, which has to know how to re-target all of the links in the text. And it needs to know which page they are on...

**Comment by ehuss** [comment] 2019-05-17 13:20
I believe all print links are now fixed via #866 and #871.

**Closed by ehuss** 2019-05-17 13:20 UTC
